application: dnikku1
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /.*
  script: app.py
  login: required


skip_files: |
 ^(.*/)?(
 (\.git*)|
 (.*/docs/.*)|
 (.*/(ez_)?setup.py)|
 (.*/(MANIFEST.in|README.txt|setup.cfg))|
 (.*\.pth)|
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 )$
