application: dnikku1
version: 2
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: frontend/static/
- url: /model
  static_dir: frontend/model/
  mime_type: text/javascript
- url: /api/.*
  script: app.py
- url: /.*
  script: app.py
  login: required

libraries:
- name: jinja2
  version: latest

builtins:
- deferred: on


skip_files: |
 ^(.*/)?(
 (\.git*)|
 (frontend_charp/.*)|
 (.*/docs/.*)|
 (.*/(ez_)?setup.py)|
 (.*/(MANIFEST.in|README.txt|setup.cfg))|
 (.*\.pth)|
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 )$
